*** Settings ***
Resource        ../keywords.robot

*** Variables ***
${USE_REMOTE_CONFIG} 	${true}
${BROKER_APP_NAME} 		${BROKER_APP_NAME_REMOTE_CONFIG}
${BROKER_HOSTNAME} 		${BROKER_HOSTNAME_REMOTE_CONFIG}
${BROKER_NAME} 			${BROKER_NAME_REMOTE_CONFIG}